exclude: >
    (?x)^(
        \.tox/.*
    )$
default_language_version:
  python: python3.7
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types: [python]
