sudo: required
dist: xenial
os:
- linux
services:
- docker
language: python

matrix:
  include:
    - language: generic
      env: TEST=FSSPEC
      install:
        - source ci/install.sh
      script:
        - tox -e py35,py36,py37,fuse,coverage

    - language: generic
      env: TEST=S3FS
      install:
        - source ci/install.sh
      script:
        - tox -e s3fs

    - language: generic

      env:
        - TEST=PRE-COMMIT

      install:
        - source ci/install_conda.sh
        - pip install pre-commit
        - pre-commit install --install-hooks

      script:
        - pre-commit run --all


  allow_failures:
    - language: generic
      env: TEST=GCSFS
      install:
        - source ci/install.sh
      script:
        - tox -e gcsfs

notifications:
  email: false
