sudo: required
dist: xenial
os:
- linux
services:
- docker

language: generic
env:
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=coverage
  - TOXENV=lint
  - TOXENV=s3fs
  - TOXENV=gcsfs
  - TOXENV=fuse
install:
  - source ci/install.sh
script:
  - tox

notifications:
  email: false
