name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp
  - pip
  - requests
  - zstandard
  - python-snappy
  - lz4
  - pyftpdlib
  - cloudpickle
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-vcr
  - python-libarchive-c
  - numpy
  - nomkl
